AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  Endpoint:
    Type: String
  Index:
    Type: String
  User:
    Type: String
  Password:
    Type: String
Resources:
  Search:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          ENDPOINT: !Ref Endpoint
          INDEX: !Ref Index
          USER: !Ref User
          PASSWORD: !Ref Password
      Events:
        GetAlias:
          Type: Api
          Properties:
            Path: "/{q}"
            Method: get
